name: Flutter CI

on:
  push:
    branches:
      - prod_release
      - merge_section

  pull_request:
    branches:
      - prod_release
      - merge_section

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          cache: true

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze code
        run: flutter analyze

      - name: Run tests
        run: flutter test

      - name: Build debug APK
        run: flutter build apk --debug
